version: '3.5'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dump:/tmp/dump
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
volumes:
  db_data_dev: